language: node_js
dist: trusty
node_js:
  - "6"
  - "7"
install:
  - npm install
script:
  - npm run test
notifications:
  email:
    on_failure: change
cache:
  yarn: true
  directories:
    - node_modules
